spring:
  datasource:
    url: jdbc:mysql://<RDS-ENDPOINT>:3306/user_service_db
    username: <your-db-username>
    password: <your-db-password>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
